### ISSUE TITLE
Support for 3.36

### ISSUE THREAD

**Issue by jkotra** [ewlsh/dynamic-panel-transparency#111]
Hi,

this extension does not work with Gnome 3.36

please add support to it.

**Comment by manhtukhang** [comment]
Same
- Gnome shell version: `3.36.0`
- Error logs:
```js
Mar 09 15:54:55 MT gnome-shell[12030]: JS ERROR: Extension dynamic-panel-transparency@rockon999.github.io: TypeError: Main.layoutManager.panelBox.get_anchor_point is not a function
                                       _updateBounds@/home/tukm/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/intellifade.js:115:49
                                       init@/home/tukm/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/intellifade.js:37:5
                                       enable@/home/tukm/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/extension.js:45:17
                                       _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
                                       loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
                                       callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
                                       gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
```

**Comment by afrapiqin** [comment]
i don't know much but i like to confirm that this extension does working in 3.36 if i don't use  Main.layoutManager.panelBox.get_anchor_point() function and manually set anchor_y in intellifade.js

**Comment by onlymash** [comment]
> ~/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/intellifade.js

change
```
    let anchor_y = -Main.layoutManager.panelBox.get_anchor_point()[1];
    let pivot_y = -Main.layoutManager.panelBox.get_pivot_point()[1];

    // Adjust for bottom panel.
    if (anchor_y > 0) {
        this.panel_bounds.y = anchor_y;
        this.panel_bounds.is_top = false;
    } else if (pivot_y > 0) {
        this.panel_bounds.y = pivot_y;
        this.panel_bounds.is_top = false;
    }
```
to
```
    let pivot_y = -Main.layoutManager.panelBox.get_pivot_point()[1];

    // Adjust for bottom panel.
    if (pivot_y > 0) {
        this.panel_bounds.y = pivot_y;
        this.panel_bounds.is_top = false;
    }
```

**Comment by jkotra** [comment]
> > ~/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/intellifade.js
> 
> change
> 
> ```
>     let anchor_y = -Main.layoutManager.panelBox.get_anchor_point()[1];
>     let pivot_y = -Main.layoutManager.panelBox.get_pivot_point()[1];
> 
>     // Adjust for bottom panel.
>     if (anchor_y > 0) {
>         this.panel_bounds.y = anchor_y;
>         this.panel_bounds.is_top = false;
>     } else if (pivot_y > 0) {
>         this.panel_bounds.y = pivot_y;
>         this.panel_bounds.is_top = false;
>     }
> ```
> 
> to
> 
> ```
>     let pivot_y = -Main.layoutManager.panelBox.get_pivot_point()[1];
> 
>     // Adjust for bottom panel.
>     if (pivot_y > 0) {
>         this.panel_bounds.y = pivot_y;
>         this.panel_bounds.is_top = false;
>     }
> ```

perhaps make a pull request?

**Comment by jjgalvez** [comment]
Applied this patch and the extension is working again with 3.36
Thank you

**Comment by ferlanero** [comment]
I have applied the patch above, but nothing has changed. dynamic-panel-transparency still not working Do you have changed anything more?

**Comment by arthurflor23** [comment]
I changed here and it worked! (Arch + Gnome 3.36).
I sent the pull request. Thanks!

**Comment by rockon999** [comment]
Hi all! I want to thank you all so much for the work done here, life has been a little crazy for me.

I'll merge in the changes asap and push to GNOME Extensions.

I do have an exciting revamp of the extension for 3.36 in the works which fixes lag issues, lock screen incompatibilities, and focuses on automatic settings instead of manual configuration.

**Comment by ernesto1** [comment]
@rockon999  out of curiosity, how long do new code pushes take to reflect on the gnome extensions site?

I'm glad this is being addressed.  Would like to update the extension from the site directly when available.

**Comment by JeRaF** [comment]
> > ~/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/intellifade.js
> 
> изменение
> 
> ```
>     let anchor_y = -Main.layoutManager.panelBox.get_anchor_point()[1];
>     let pivot_y = -Main.layoutManager.panelBox.get_pivot_point()[1];
> 
>     // Adjust for bottom panel.
>     if (anchor_y > 0) {
>         this.panel_bounds.y = anchor_y;
>         this.panel_bounds.is_top = false;
>     } else if (pivot_y > 0) {
>         this.panel_bounds.y = pivot_y;
>         this.panel_bounds.is_top = false;
>     }
> ```
> 
> в
> 
> ```
>     let pivot_y = -Main.layoutManager.panelBox.get_pivot_point()[1];
> 
>     // Adjust for bottom panel.
>     if (pivot_y > 0) {
>         this.panel_bounds.y = pivot_y;
>         this.panel_bounds.is_top = false;
>     }
> ```

Solus 4.1+Gnome 3.36.1 etot sposob ne rabotayet. i de zavisayet
61/5000
Solus 4.1 + Gnome 3.36.1 this method does not work. and de freezes

**Comment by verndog** [comment]
The above fix doesn't work with the newest gnome-shell:
$ apt show gnome-shell
Package: gnome-shell
Version: 3.36.1-5ubuntu2
It works with Version: 3.36.1-5ubuntu1

**Comment by theHimanshuShekhar** [comment]
yes the patch doesn't work with news gnome shell in 20.04

**Comment by Iyxan23** [comment]
same

**Comment by danielsanfr** [comment]
Please fix this problem.

**Comment by danielsanfr** [comment]
There is 2 PRs waiting for merge:
* https://github.com/rockon999/dynamic-panel-transparency/pull/112
* https://github.com/rockon999/dynamic-panel-transparency/pull/114

**Comment by rockon999** [comment]
@danielsanfr Thank you for your interest!

Due to the pandemic, I've had to prioritize other aspects of my life. The academic semester just wrapped up for me, so I will try to get to these PRs this week.

**Comment by danielsanfr** [comment]
You are correct in prioritizing what is most important! Everyone has to do the same.

Take your time to do this. Do it as long as you can.

Thank you very much in advance.

**Comment by rockon999** [comment]
Hi everyone, sorry for the delay.

Please test #115 if you can, I'm running it locally and it appears to resolve all issues for me.

**Comment by theeomm** [comment]
> Hi everyone, sorry for the delay.
> 
> Please test #115 if you can, I'm running it locally and it appears to resolve all issues for me.

Works for me too

**Comment by verndog** [comment]
Yes it works on version 3.36.2.

**Comment by NOOBLINUXUSER** [comment]
> Hi everyone, sorry for the delay.
> 
> Please test #115 if you can, I'm running it locally and it appears to resolve all issues for me.

as the name implies, i am noob. how do you do  run it locally

**Comment by theeomm** [comment]
@NOOBLINUXUSER 

1. Clone the fix-bounds branch from the repo `git clone https://github.com/rockon999/dynamic-panel-transparency.git -b fix-bounds` or [download](https://github.com/ewlsh/dynamic-panel-transparency/archive/fix-bounds.zip) it

2. Move the `dynamic-panel-transparency@rockon999.github.io` folder to `~/.local/share/gnome-shell/extensions/`

3. Finally, reload your shell `Alt + F2` `r` `Enter` 

These instructions are included in the README file .

**Comment by danielsanfr** [comment]
Here it is working perfectly again. Thank you so much for doing this!

**Comment by NOOBLINUXUSER** [comment]
> @NOOBLINUXUSER
> 
> 1. Clone the fix-bounds branch from the repo `git clone https://github.com/rockon999/dynamic-panel-transparency.git -b fix-bounds` or [download](https://github.com/ewlsh/dynamic-panel-transparency/archive/fix-bounds.zip) it
> 2. Move the `dynamic-panel-transparency@rockon999.github.io` folder to `~/.local/share/gnome-shell/extensions/`
> 3. Finally, reload your shell `Alt + F2` `r` `Enter`
> 
> These instructions are included in the README file .

some how this worked for me (using POP OS), before you replied. thanks though-appreciate.

**Comment by ewlsh** [comment]
Hi all, I'll package and ship to GNOME Extensions soon.

**Comment by henrik-wittenberg** [comment]
The extension, which I installed from extensions.gnome.org, is not working on GNOME 3.36/X11 Manjaro.

Error message according to looking glass:

"TypeError: Main.layoutManager.panelBox.get_anchor_point is not a function"

**Comment by jkotra** [comment]
hi @ewlsh,

it's been over 15 days. any update on pushing/shipping fixed ver. to gnome extensions?

thanks for your work <3

**Comment by ewlsh** [comment]
It's awaiting review :)

**Comment by jkotra** [comment]
just a heads up to everyone, It's now updated on [Gnome Extension.](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/)

**Comment by onlymash** [comment]
@jkotra unable to install
![image](https://user-images.githubusercontent.com/5838634/86541447-92811780-bf3f-11ea-9552-c89bcdcdcd04.png)

**Comment by ewlsh** [comment]
@onlymash If you could provide me any logs from `journalctl` that'd be great (or the error given by GNOME Extensions)!

I would recommend deleting and installing the extension or restarting the Shell. In-place upgrades sometimes don't work correctly.

**Comment by ewlsh** [comment]
The next release will resolve some of the remaining issues, but a 3.36 release does exist.
