### ISSUE TITLE
Error in 3.38.0

### ISSUE THREAD

**Issue by MrMelon54** [ewlsh/dynamic-panel-transparency#124]
https://github.com/ewlsh/dynamic-panel-transparency/blob/cd0e7ebbd0d8df3d871134a3a4b7cba16944c5e2/dynamic-panel-transparency%40rockon999.github.io/events.js#L280

```
Oct 03 21:27:08 m21 gnome-shell[2370]: JS ERROR: Extension dynamic-panel-transparency@rockon999.github.io: Error: No signal 'allocation-changed' on object 'MetaWindowActorX11'
                                       _windowActorAdded@/home/sean/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/events.js:280:37
                                       init@/home/sean/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/events.js:58:26
                                       enable@/home/sean/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/extension.js:85:20
                                       _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                       _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:491:35
                                       _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:14
```

**Comment by britinx** [comment]
> https://github.com/ewlsh/dynamic-panel-transparency/blob/cd0e7ebbd0d8df3d871134a3a4b7cba16944c5e2/dynamic-panel-transparency%40rockon999.github.io/events.js#L280
> 
> ```
> Oct 03 21:27:08 m21 gnome-shell[2370]: JS ERROR: Extension dynamic-panel-transparency@rockon999.github.io: Error: No signal 'allocation-changed' on object 'MetaWindowActorX11'
>                                        _windowActorAdded@/home/sean/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/events.js:280:37
>                                        init@/home/sean/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/events.js:58:26
>                                        enable@/home/sean/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/extension.js:85:20
>                                        _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
>                                        _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:491:35
>                                        _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:14
> ```

Gnome, in 3.38, changed signal "allocation-changed" to "notify::allocation".

Edit events.js (usually located in ~/.local/share/gnome/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/events.js), and replace line 280 from this:

`const ac_wId = window_actor.connect('allocation-changed', (function() {`

To this:

`const ac_wId = window_actor.connect('notify::allocation', (function() {`

Reload that extension or the gnome session and check if it works.

**Comment by MrMelon54** [comment]
Yeah it works I'm going to leave a PR

**Comment by lviggiani** [comment]
Hi, I've implemented the event name change but now I get this error:

```St.get_slow_down_factor is not a function```

GS 3.38.1

**Comment by lviggiani** [comment]
Ok, I see that there's already a fix on git. I'll checkout the project from here rather than using the one on extensions.gnome.org

**Comment by lviggiani** [comment]
I confirm that using the latest git version and applying the event name change it works on GS 3.38.1 as well

**Comment by ewlsh** [comment]
Preparing a release with #128, am just downloading a test image/upgrading my shell now.

**Comment by ewlsh** [comment]
Update in [review](https://extensions.gnome.org/review/19747).

Please try the latest git!

**Comment by britinx** [comment]
> Update in [review](https://extensions.gnome.org/review/19747).
> 
> Please try the latest git!

It's working fine now, thanks!

**Comment by MrMelon54** [comment]
Can this issue be closed as it seems to be working fine?
